import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowRightIcon, BoltIcon, ChartBarSquareIcon, CheckBadgeIcon, ChevronDownIcon, HeartIcon, MapIcon, ShieldCheckIcon, SparklesIcon, UserGroupIcon } from '@heroicons/react/24/outline';
import Button from '../../components/common/Button';
import { useAuth } from '../../context/AuthContext';
import { getHomeRoute } from '../../routes/roleRoutes';

const features = [
  { icon: SparklesIcon, title: 'Predict before pressure builds', text: 'AI detects crowd buildup hours ahead, turning uncertainty into early action.', tone: 'bg-orange-50 text-saffron' },
  { icon: MapIcon, title: 'Guide every step safely', text: 'Live route guidance quietly reroutes pilgrims around congested corridors.', tone: 'bg-emerald-50 text-forest' },
  { icon: HeartIcon, title: 'Bring care closer', text: 'Water, rest and medical support are positioned before a need becomes urgent.', tone: 'bg-red-50 text-red-600' },
];

const steps = [
  { number: '01', title: 'Sense the journey', text: 'Live movement, weather and camp signals create one shared view of the Wari.' },
  { number: '02', title: 'See what is next', text: 'Prediction models flag crowd pressure, shortages and weather risks in advance.' },
  { number: '03', title: 'Protect together', text: 'Pilgrims, teams and officials get the right action at the right moment.' },
];

const testimonials = [
  { quote: 'The safer-route suggestion arrived before our group reached the bottleneck. It made the day feel calm.', person: 'Savitri Tai', role: 'Warkari, Pune' },
  { quote: 'One live picture of route, resources and response teams changes how we coordinate an entire district.', person: 'A. Deshmukh', role: 'Municipal control room' },
];

function JourneyIllustration() {
  return <div className="relative mx-auto h-[390px] w-full max-w-[600px] sm:h-[460px]"><div className="absolute inset-8 rounded-[42%] bg-gradient-to-br from-orange-100 via-amber-50 to-emerald-100 blur-2xl" /><div className="absolute left-[5%] top-[18%] h-24 w-24 rounded-full border-[16px] border-white/70 bg-orange-200/65 sm:h-36 sm:w-36" /><div className="absolute right-[5%] top-[5%] h-20 w-20 rounded-full bg-emerald-200/70 blur-sm" /><div className="absolute bottom-[5%] left-[15%] h-24 w-24 rounded-full bg-amber-200/70 blur-sm" />
    <svg className="absolute inset-0 h-full w-full" viewBox="0 0 600 460" fill="none" aria-hidden="true"><path d="M102 392C139 341 149 299 203 279C272 254 283 297 345 253C412 205 407 164 481 117" stroke="#008C45" strokeWidth="16" strokeLinecap="round" /><path d="M102 392C139 341 149 299 203 279C272 254 283 297 345 253C412 205 407 164 481 117" stroke="white" strokeOpacity=".8" strokeWidth="5" strokeDasharray="1 20" strokeLinecap="round" /></svg>
    <motion.div initial={{ scale: .6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ delay: .25 }} className="absolute left-[10%] top-[61%] rounded-2xl border border-white/80 bg-white/90 p-3 shadow-float backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Current flow</p><div className="mt-1 flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-forest" /><span className="text-sm font-bold text-ink">Comfortable</span></div></motion.div>
    <motion.div initial={{ y: 16, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .45 }} className="absolute right-[2%] top-[28%] w-48 rounded-2xl border border-white/90 bg-white/95 p-4 shadow-float"><div className="flex items-center justify-between"><span className="text-xs font-bold text-ink">AI route watch</span><SparklesIcon className="h-4 w-4 text-saffron" /></div><p className="mt-3 text-2xl font-bold text-forest">92%</p><p className="mt-1 text-xs leading-5 text-slate-500">confidence in your safer path</p></motion.div>
    <motion.div animate={{ y: [0, -7, 0] }} transition={{ repeat: Infinity, duration: 3.5, ease: 'easeInOut' }} className="absolute right-[23%] top-[10%] grid h-13 w-13 place-items-center rounded-2xl border-4 border-white bg-saffron text-lg font-bold text-white shadow-float">व</motion.div>
    <div className="absolute bottom-[4%] right-[16%] grid h-14 w-14 place-items-center rounded-full border-4 border-white bg-forest text-white shadow-float"><ShieldCheckIcon className="h-7 w-7" /></div>
  </div>;
}

export default function LandingPage() {
  const { role } = useAuth();
  const dashboardPath = role ? getHomeRoute(typeof role === 'string' ? role : role.id) : '/select-role';

  return <div className="overflow-hidden bg-[#FCFDFC] text-ink"><header className="absolute inset-x-0 top-0 z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link to="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-saffron text-lg font-bold text-white shadow-[0_8px_20px_rgba(255,122,0,.3)]">व</div><div><p className="text-lg font-bold tracking-tight">VariSetu</p><p className="-mt-0.5 text-[10px] font-bold uppercase tracking-[.13em] text-forest">Wari 2026</p></div></Link><nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 md:flex"><a href="#how-it-works" className="hover:text-saffron">How it works</a><a href="#impact" className="hover:text-saffron">Impact</a><a href="#for-authorities" className="hover:text-saffron">For authorities</a></nav><Link to={dashboardPath}><Button className="px-4 py-2.5">Open live dashboard <ArrowRightIcon className="h-4 w-4" /></Button></Link></header>

    <main><section className="relative isolate min-h-[760px] overflow-hidden px-5 pb-16 pt-36 sm:px-8 lg:min-h-[790px]"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_74%_34%,rgba(215,244,221,.9),transparent_26%),radial-gradient(circle_at_18%_2%,rgba(255,226,196,.8),transparent_34%)]" /><div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden" aria-hidden="true" style={{
          maskImage: 'radial-gradient(ellipse 60% 92% at 50% 50%, rgba(0,0,0,1) 0%, rgba(0,0,0,0.9) 22%, rgba(0,0,0,0.55) 50%, rgba(0,0,0,0.18) 75%, transparent 92%)',
          WebkitMaskImage: 'radial-gradient(ellipse 60% 92% at 50% 50%, rgba(0,0,0,1) 0%, rgba(0,0,0,0.9) 22%, rgba(0,0,0,0.55) 50%, rgba(0,0,0,0.18) 75%, transparent 92%)'
        }}>
        <img
          src="/assets/vitthal-silhouette.svg"
          alt=""
          className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 h-[88%] w-auto object-contain max-lg:h-[82%] max-md:h-[72%] max-sm:h-[58%] max-sm:top-[65%]"
          style={{
            filter: 'brightness(1.55) contrast(0.2) saturate(0) sepia(0.045) hue-rotate(5deg) blur(4px)',
            opacity: 0.105
          }}
        />
      </div><div className="mx-auto grid max-w-7xl items-center gap-8 lg:grid-cols-[1.02fr_.98fr]"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><div className="inline-flex items-center gap-2 rounded-full border border-orange-100 bg-white/70 px-3 py-1.5 text-xs font-bold text-saffron shadow-sm backdrop-blur"><span className="h-2 w-2 animate-pulse rounded-full bg-saffron" />AI-powered Wari coordination</div><h1 className="mt-7 max-w-3xl text-5xl font-bold leading-[1.03] tracking-[-.055em] text-ink sm:text-6xl lg:text-7xl">A safer Wari begins <span className="serif font-semibold text-saffron">before</span> the crowd arrives.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">VariSetu predicts crowd pressure, guides pilgrims to safer paths, and helps every response team act earlier — together.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to={dashboardPath}><Button className="w-full sm:w-auto" icon={BoltIcon}>See your live journey</Button></Link><a href="#how-it-works"><Button className="w-full sm:w-auto" variant="outline">See how it works <ChevronDownIcon className="h-4 w-4" /></Button></a></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-4"><div><p className="text-2xl font-bold text-ink">1.8M+</p><p className="text-xs font-semibold text-slate-500">Pilgrims supported</p></div><div className="hidden h-9 w-px bg-slate-200 sm:block" /><div><p className="text-2xl font-bold text-ink">92%</p><p className="text-xs font-semibold text-slate-500">Forecast confidence</p></div><div className="hidden h-9 w-px bg-slate-200 sm:block" /><div><p className="text-2xl font-bold text-ink">36 min</p><p className="text-xs font-semibold text-slate-500">Earlier response time</p></div></div></motion.div><JourneyIllustration /></div></section>

      <section className="border-y border-slate-100 bg-white py-7"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 text-center sm:flex-row sm:px-8 sm:text-left"><p className="text-sm font-semibold text-slate-500">Built for every hand that keeps the Wari moving</p><div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs font-bold uppercase tracking-[.16em] text-slate-400"><span>Warkaris</span><span>Municipalities</span><span>Medical teams</span><span>Police</span><span>Volunteers</span></div></div></section>

      <section id="impact" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="max-w-2xl"><p className="eyebrow">One shared safety net</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Less uncertainty on the road. More care where it matters.</h2><p className="mt-4 leading-7 text-slate-500">VariSetu connects movement, need and response in one calm, clear experience — no matter which side of the journey you serve.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map((feature, index) => <motion.article whileHover={{ y: -5 }} key={feature.title} className="surface p-7" initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }}><div className={`grid h-12 w-12 place-items-center rounded-2xl ${feature.tone}`}><feature.icon className="h-6 w-6" /></div><h3 className="mt-7 text-xl font-bold tracking-tight">{feature.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{feature.text}</p><div className="mt-6 flex items-center gap-2 text-sm font-bold text-saffron">Explore capability <ArrowRightIcon className="h-4 w-4" /></div></motion.article>)}</div></section>

      <section id="how-it-works" className="bg-[#153225] px-5 py-24 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow !text-[#A7E6B8]">Predict → Prevent → Protect</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Quiet intelligence for a journey that moves millions.</h2><p className="mt-5 max-w-md leading-7 text-emerald-50/70">A continuous feedback loop turns signals from the route into simple, timely actions that keep people flowing safely.</p><Link to="/crowd" className="mt-8 inline-block"><Button variant="primary">Explore live crowd watch</Button></Link></div><div className="grid gap-4">{steps.map((step, index) => <motion.div initial={{ opacity: 0, x: 16 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} key={step.number} className="grid gap-4 rounded-3xl border border-white/10 bg-white/[.06] p-6 sm:grid-cols-[70px_1fr]"><p className="text-3xl font-bold text-[#A7E6B8]">{step.number}</p><div><h3 className="text-lg font-bold">{step.title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-emerald-50/65">{step.text}</p></div></motion.div>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="surface overflow-hidden bg-gradient-to-br from-white to-orange-50 p-7 sm:p-10"><div className="grid items-center gap-10 lg:grid-cols-[1fr_.9fr]"><div><p className="eyebrow">A glance ahead</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">From insight to a safer next step.</h2><p className="mt-4 max-w-lg leading-7 text-slate-500">A pilgrim sees a clear route. A control room sees the reason behind it. Everyone stays ahead of pressure — without the noise.</p><div className="mt-7 flex flex-wrap gap-3"><span className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-600 shadow-sm">Live crowd density</span><span className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-600 shadow-sm">Resource forecast</span><span className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-600 shadow-sm">SOS coordination</span></div></div><div className="rounded-[28px] bg-ink p-4 shadow-float"><div className="rounded-2xl bg-[#f7faf8] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Your route today</p><p className="mt-1 text-lg font-bold">Alandi → Saswad</p></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-forest">Safer path</span></div><div className="mt-4 h-32 rounded-xl bg-[linear-gradient(135deg,#d8f1db,#e9f4ec_55%,#fce5cc)] p-4"><div className="flex h-full items-end gap-2"><span className="h-7 w-7 rounded-full border-4 border-white bg-forest" /><div className="mb-3 h-2 flex-1 rounded-full bg-forest" /><span className="h-7 w-7 rounded-full border-4 border-white bg-saffron" /></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><p className="text-lg font-bold">8.4 km</p><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Distance</p></div><div><p className="text-lg font-bold">2h 18m</p><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">ETA</p></div><div><p className="text-lg font-bold text-forest">Low</p><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Risk</p></div></div></div></div></div></div></section>

      <section id="for-authorities" className="bg-[#F1F7F1] px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="eyebrow">Designed for coordinated action</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">One operating picture for every authority.</h2></div><Link to="/admin"><Button variant="outline">View command centre <ArrowRightIcon className="h-4 w-4" /></Button></Link></div><div className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl bg-forest p-7 text-white"><ChartBarSquareIcon className="h-8 w-8 text-emerald-200" /><h3 className="mt-12 text-2xl font-bold">Act on the route, not after the report.</h3><p className="mt-3 max-w-md text-sm leading-6 text-emerald-50/75">Prioritize patrols, camps and supplies from one live command view — with clear forecasts and decision-ready alerts.</p><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-bold">24</p><p className="mt-1 text-xs text-emerald-50/65">signals connected</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-bold">4.8×</p><p className="mt-1 text-xs text-emerald-50/65">faster triage</p></div></div></article><div className="grid gap-5 sm:grid-cols-2"><article className="surface p-6"><UserGroupIcon className="h-7 w-7 text-saffron" /><h3 className="mt-8 font-bold">See the full flow</h3><p className="mt-2 text-sm leading-6 text-slate-500">Zone-level density, movement and pressure in one map.</p></article><article className="surface p-6"><ShieldCheckIcon className="h-7 w-7 text-forest" /><h3 className="mt-8 font-bold">Respond with confidence</h3><p className="mt-2 text-sm leading-6 text-slate-500">Send the nearest capable team with a route that stays clear.</p></article></div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-5 lg:grid-cols-2">{testimonials.map((item) => <figure key={item.person} className="surface p-7"><CheckBadgeIcon className="h-7 w-7 text-saffron" /><blockquote className="mt-6 text-xl font-semibold leading-8 text-ink">“{item.quote}”</blockquote><figcaption className="mt-6"><p className="text-sm font-bold">{item.person}</p><p className="mt-1 text-xs text-slate-500">{item.role}</p></figcaption></figure>)}</div></section>
    </main><footer className="bg-ink px-5 py-10 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row"><div><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-saffron font-bold">व</div><p className="text-lg font-bold">VariSetu</p></div><p className="mt-3 max-w-sm text-sm leading-6 text-slate-400">Guiding a safer, calmer Wari — one informed decision at a time.</p></div><div className="flex flex-wrap gap-x-6 gap-y-2 self-end text-sm font-semibold text-slate-400"><span>v0.1.0</span><span className="text-slate-600">·</span><span>Wari Hackathon 2026</span><span className="text-slate-600">·</span><a href="#" className="hover:text-white">About</a><span className="text-slate-600">·</span><a href="#" className="hover:text-white">Contact</a><span className="text-slate-600">·</span><a href="#" className="hover:text-white">Privacy</a></div></div></footer></div>;
}
